[template]
src="keycloak-proxy-config.json.tmpl"
dest="/opt/jboss/keycloak-proxy-config/config.json"
keys= [
    "/self/service/metadata/targeturl",
    "/self/service/metadata/keycloak-realm",
    "/self/service/metadata/keycloak-clientid",
    "/self/service/metadata/keycloak-url",
    "/self/service/metadata/keycloak-secret"
]
