[template]
src="keycloak-proxy-config.json.tmpl"
dest="/opt/jboss/keycloak-proxy-config/proxy.json"
keys= [
    "/self/service/metadata/targeturl",
    "/self/service/metadata/adapter-config",
    "/self/service/metadata/constraints",
]
